//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Folios", Namespace="http://schemas.datacontract.org/2004/07/CertificadorWs.Business")]
    public partial class Folios : object
    {
        
        private ServiceReference1.Folios.R RespuestaField;
        
        private string UUDIField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Folios.R Respuesta
        {
            get
            {
                return this.RespuestaField;
            }
            set
            {
                this.RespuestaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUDI
        {
            get
            {
                return this.UUDIField;
            }
            set
            {
                this.UUDIField = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Folios.R", Namespace="http://schemas.datacontract.org/2004/07/CertificadorWs.Business")]
        public enum R : int
        {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Aceptacion = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Rechazo = 1,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpresaNtLink", Namespace="http://schemas.datacontract.org/2004/07/CertificadorWs.Business")]
    public partial class EmpresaNtLink : object
    {
        
        private string CiudadField;
        
        private string ColoniaField;
        
        private string ContactoField;
        
        private string CpField;
        
        private string CurpField;
        
        private string DireccionField;
        
        private string EmailField;
        
        private string EstadoField;
        
        private System.DateTime FechaContratoField;
        
        private int FoliosField;
        
        private string RazonSocialField;
        
        private string RegimenFiscalField;
        
        private string RfcField;
        
        private int SucursalesField;
        
        private string TelefonoField;
        
        private int TimbresContratadosField;
        
        private int UsuariosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad
        {
            get
            {
                return this.CiudadField;
            }
            set
            {
                this.CiudadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Colonia
        {
            get
            {
                return this.ColoniaField;
            }
            set
            {
                this.ColoniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contacto
        {
            get
            {
                return this.ContactoField;
            }
            set
            {
                this.ContactoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cp
        {
            get
            {
                return this.CpField;
            }
            set
            {
                this.CpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Curp
        {
            get
            {
                return this.CurpField;
            }
            set
            {
                this.CurpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaContrato
        {
            get
            {
                return this.FechaContratoField;
            }
            set
            {
                this.FechaContratoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Folios
        {
            get
            {
                return this.FoliosField;
            }
            set
            {
                this.FoliosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial
        {
            get
            {
                return this.RazonSocialField;
            }
            set
            {
                this.RazonSocialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegimenFiscal
        {
            get
            {
                return this.RegimenFiscalField;
            }
            set
            {
                this.RegimenFiscalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rfc
        {
            get
            {
                return this.RfcField;
            }
            set
            {
                this.RfcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sucursales
        {
            get
            {
                return this.SucursalesField;
            }
            set
            {
                this.SucursalesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimbresContratados
        {
            get
            {
                return this.TimbresContratadosField;
            }
            set
            {
                this.TimbresContratadosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Usuarios
        {
            get
            {
                return this.UsuariosField;
            }
            set
            {
                this.UsuariosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteNtLink", Namespace="http://schemas.datacontract.org/2004/07/CertificadorWs.Business")]
    public partial class ClienteNtLink : object
    {
        
        private string CiudadField;
        
        private string ColoniaField;
        
        private string ContactoField;
        
        private string CpField;
        
        private string DireccionField;
        
        private string EmailField;
        
        private int EmpresasField;
        
        private string EstadoField;
        
        private System.DateTime FechaContratoField;
        
        private string RazonSocialField;
        
        private string RegimenFiscalField;
        
        private string RfcField;
        
        private int SucursalesField;
        
        private string TelefonoField;
        
        private int TimbresConsumidosField;
        
        private int TimbresContratadosField;
        
        private int UsuariosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad
        {
            get
            {
                return this.CiudadField;
            }
            set
            {
                this.CiudadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Colonia
        {
            get
            {
                return this.ColoniaField;
            }
            set
            {
                this.ColoniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contacto
        {
            get
            {
                return this.ContactoField;
            }
            set
            {
                this.ContactoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cp
        {
            get
            {
                return this.CpField;
            }
            set
            {
                this.CpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Empresas
        {
            get
            {
                return this.EmpresasField;
            }
            set
            {
                this.EmpresasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaContrato
        {
            get
            {
                return this.FechaContratoField;
            }
            set
            {
                this.FechaContratoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial
        {
            get
            {
                return this.RazonSocialField;
            }
            set
            {
                this.RazonSocialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegimenFiscal
        {
            get
            {
                return this.RegimenFiscalField;
            }
            set
            {
                this.RegimenFiscalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rfc
        {
            get
            {
                return this.RfcField;
            }
            set
            {
                this.RfcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sucursales
        {
            get
            {
                return this.SucursalesField;
            }
            set
            {
                this.SucursalesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimbresConsumidos
        {
            get
            {
                return this.TimbresConsumidosField;
            }
            set
            {
                this.TimbresConsumidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimbresContratados
        {
            get
            {
                return this.TimbresContratadosField;
            }
            set
            {
                this.TimbresContratadosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Usuarios
        {
            get
            {
                return this.UsuariosField;
            }
            set
            {
                this.UsuariosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimbradoResponse", Namespace="http://schemas.datacontract.org/2004/07/CertificadorWs")]
    public partial class TimbradoResponse : object
    {
        
        private string CadenaTimbreField;
        
        private string CfdiField;
        
        private string DescripcionErrorField;
        
        private string QrCodeBase64Field;
        
        private bool ValidoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CadenaTimbre
        {
            get
            {
                return this.CadenaTimbreField;
            }
            set
            {
                this.CadenaTimbreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cfdi
        {
            get
            {
                return this.CfdiField;
            }
            set
            {
                this.CfdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionError
        {
            get
            {
                return this.DescripcionErrorField;
            }
            set
            {
                this.DescripcionErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QrCodeBase64
        {
            get
            {
                return this.QrCodeBase64Field;
            }
            set
            {
                this.QrCodeBase64Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Valido
        {
            get
            {
                return this.ValidoField;
            }
            set
            {
                this.ValidoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaCancelacion", Namespace="http://schemas.datacontract.org/2004/07/CertificadorWs.Business")]
    public partial class RespuestaCancelacion : object
    {
        
        private string AcuseField;
        
        private string MensajeErrorField;
        
        private ServiceReference1.StatusUuid[] StatusUuidsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Acuse
        {
            get
            {
                return this.AcuseField;
            }
            set
            {
                this.AcuseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError
        {
            get
            {
                return this.MensajeErrorField;
            }
            set
            {
                this.MensajeErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.StatusUuid[] StatusUuids
        {
            get
            {
                return this.StatusUuidsField;
            }
            set
            {
                this.StatusUuidsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusUuid", Namespace="http://schemas.datacontract.org/2004/07/CertificadorWs.Business")]
    public partial class StatusUuid : object
    {
        
        private string StatusField;
        
        private string UuidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uuid
        {
            get
            {
                return this.UuidField;
            }
            set
            {
                this.UuidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoConsulta", Namespace="http://schemas.datacontract.org/2004/07/CertificadorWs")]
    public partial class ResultadoConsulta : object
    {
        
        private string AcuseCancelacionField;
        
        private string AcuseEnvioField;
        
        private string ComprobanteField;
        
        private ServiceReference1.StatusComprobante StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcuseCancelacion
        {
            get
            {
                return this.AcuseCancelacionField;
            }
            set
            {
                this.AcuseCancelacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcuseEnvio
        {
            get
            {
                return this.AcuseEnvioField;
            }
            set
            {
                this.AcuseEnvioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comprobante
        {
            get
            {
                return this.ComprobanteField;
            }
            set
            {
                this.ComprobanteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.StatusComprobante Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusComprobante", Namespace="http://schemas.datacontract.org/2004/07/CertificadorWs")]
    public enum StatusComprobante : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoEncontrado = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EnProceso = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enviado = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelado = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://ntlink.com.mx/IServicioTimbrado", ConfigurationName="ServiceReference1.IServicioTimbrado")]
    public interface IServicioTimbrado
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/ConsultaSaldo", ReplyAction="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/ConsultaSaldoResponse")]
        System.Threading.Tasks.Task<int> ConsultaSaldoAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/ConsultaAceptacionRecha" +
            "zo", ReplyAction="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/ConsultaAceptacionRecha" +
            "zoResponse")]
        System.Threading.Tasks.Task<string> ConsultaAceptacionRechazoAsync(string userName, string password, string rfcEmisor, string rfcReceptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/ProcesarRespuestaAcepta" +
            "cionRechazo", ReplyAction="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/ProcesarRespuestaAcepta" +
            "cionRechazoResponse")]
        System.Threading.Tasks.Task<string> ProcesarRespuestaAceptacionRechazoAsync(string userName, string password, ServiceReference1.Folios[] uuid, string rfcEmisor, string rfcReceptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/ConsultaEstatusCFDI", ReplyAction="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/ConsultaEstatusCFDIResp" +
            "onse")]
        System.Threading.Tasks.Task<string> ConsultaEstatusCFDIAsync(string userName, string password, string expresion);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/ConsultaCFDIRelacionado" +
            "s", ReplyAction="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/ConsultaCFDIRelacionado" +
            "sResponse")]
        System.Threading.Tasks.Task<string> ConsultaCFDIRelacionadosAsync(string userName, string password, string uuid, string rfcEmisor, string rfcReceptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/RegistraEmpresa", ReplyAction="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/RegistraEmpresaResponse" +
            "")]
        System.Threading.Tasks.Task RegistraEmpresaAsync(string userName, string password, ServiceReference1.EmpresaNtLink empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/BajaEmpresa", ReplyAction="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/BajaEmpresaResponse")]
        System.Threading.Tasks.Task BajaEmpresaAsync(string userName, string password, string rfcEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/ObtenerDatosCliente", ReplyAction="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/ObtenerDatosClienteResp" +
            "onse")]
        System.Threading.Tasks.Task<ServiceReference1.ClienteNtLink> ObtenerDatosClienteAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/ObtenerEmpresas", ReplyAction="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/ObtenerEmpresasResponse" +
            "")]
        System.Threading.Tasks.Task<ServiceReference1.EmpresaNtLink[]> ObtenerEmpresasAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/TimbraCfdiQr", ReplyAction="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/TimbraCfdiQrResponse")]
        System.Threading.Tasks.Task<ServiceReference1.TimbradoResponse> TimbraCfdiQrAsync(string userName, string password, string comprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/TimbraCfdiQrSinSello", ReplyAction="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/TimbraCfdiQrSinSelloRes" +
            "ponse")]
        System.Threading.Tasks.Task<ServiceReference1.TimbradoResponse> TimbraCfdiQrSinSelloAsync(string userName, string password, string comprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/TimbraCfdi", ReplyAction="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/TimbraCfdiResponse")]
        System.Threading.Tasks.Task<string> TimbraCfdiAsync(string userName, string password, string comprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/TimbraCfdiSinSello", ReplyAction="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/TimbraCfdiSinSelloRespo" +
            "nse")]
        System.Threading.Tasks.Task<string> TimbraCfdiSinSelloAsync(string userName, string password, string comprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/TimbraRetencion", ReplyAction="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/TimbraRetencionResponse" +
            "")]
        System.Threading.Tasks.Task<string> TimbraRetencionAsync(string userName, string password, string comprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/TimbraRetencionSinSello" +
            "", ReplyAction="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/TimbraRetencionSinSello" +
            "Response")]
        System.Threading.Tasks.Task<string> TimbraRetencionSinSelloAsync(string userName, string password, string comprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/TimbraRetencionQr", ReplyAction="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/TimbraRetencionQrRespon" +
            "se")]
        System.Threading.Tasks.Task<ServiceReference1.TimbradoResponse> TimbraRetencionQrAsync(string userName, string password, string comprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/CancelaRetencion", ReplyAction="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/CancelaRetencionRespons" +
            "e")]
        System.Threading.Tasks.Task<string> CancelaRetencionAsync(string userName, string password, string uuid, string rfc, string motivo, string folioSustituto);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/CancelaCfdi", ReplyAction="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/CancelaCfdiResponse")]
        System.Threading.Tasks.Task<string> CancelaCfdiAsync(string userName, string password, string uuid, string motivo, string folioSustituto, string rfc, string expresion, string rfcReceptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/CancelaCfdiOtrosPACs", ReplyAction="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/CancelaCfdiOtrosPACsRes" +
            "ponse")]
        System.Threading.Tasks.Task<string> CancelaCfdiOtrosPACsAsync(string uuid, string motivo, string folioSustituto, string rfcEmisor, string expresion, string rfcReceptor, string Base64Cer, string Base64Key, string PasswordKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/CancelaCfdiRequest", ReplyAction="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/CancelaCfdiRequestRespo" +
            "nse")]
        System.Threading.Tasks.Task<ServiceReference1.RespuestaCancelacion> CancelaCfdiRequestAsync(string userName, string password, string requestCancelacion, string expresion, string uuid, string rfcReceptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/ObtenerStatusUuid", ReplyAction="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/ObtenerStatusUuidRespon" +
            "se")]
        System.Threading.Tasks.Task<ServiceReference1.ResultadoConsulta> ObtenerStatusUuidAsync(string userName, string password, string uuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/ObtenerStatusHash", ReplyAction="https://ntlink.com.mx/IServicioTimbrado/IServicioTimbrado/ObtenerStatusHashRespon" +
            "se")]
        System.Threading.Tasks.Task<ServiceReference1.ResultadoConsulta> ObtenerStatusHashAsync(string userName, string password, string hash);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServicioTimbradoChannel : ServiceReference1.IServicioTimbrado, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServicioTimbradoClient : System.ServiceModel.ClientBase<ServiceReference1.IServicioTimbrado>, ServiceReference1.IServicioTimbrado
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioTimbradoClient() : 
                base(ServicioTimbradoClient.GetDefaultBinding(), ServicioTimbradoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioTimbrado.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioTimbradoClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioTimbradoClient.GetBindingForEndpoint(endpointConfiguration), ServicioTimbradoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioTimbradoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioTimbradoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioTimbradoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioTimbradoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioTimbradoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> ConsultaSaldoAsync(string userName, string password)
        {
            return base.Channel.ConsultaSaldoAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task<string> ConsultaAceptacionRechazoAsync(string userName, string password, string rfcEmisor, string rfcReceptor)
        {
            return base.Channel.ConsultaAceptacionRechazoAsync(userName, password, rfcEmisor, rfcReceptor);
        }
        
        public System.Threading.Tasks.Task<string> ProcesarRespuestaAceptacionRechazoAsync(string userName, string password, ServiceReference1.Folios[] uuid, string rfcEmisor, string rfcReceptor)
        {
            return base.Channel.ProcesarRespuestaAceptacionRechazoAsync(userName, password, uuid, rfcEmisor, rfcReceptor);
        }
        
        public System.Threading.Tasks.Task<string> ConsultaEstatusCFDIAsync(string userName, string password, string expresion)
        {
            return base.Channel.ConsultaEstatusCFDIAsync(userName, password, expresion);
        }
        
        public System.Threading.Tasks.Task<string> ConsultaCFDIRelacionadosAsync(string userName, string password, string uuid, string rfcEmisor, string rfcReceptor)
        {
            return base.Channel.ConsultaCFDIRelacionadosAsync(userName, password, uuid, rfcEmisor, rfcReceptor);
        }
        
        public System.Threading.Tasks.Task RegistraEmpresaAsync(string userName, string password, ServiceReference1.EmpresaNtLink empresa)
        {
            return base.Channel.RegistraEmpresaAsync(userName, password, empresa);
        }
        
        public System.Threading.Tasks.Task BajaEmpresaAsync(string userName, string password, string rfcEmpresa)
        {
            return base.Channel.BajaEmpresaAsync(userName, password, rfcEmpresa);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ClienteNtLink> ObtenerDatosClienteAsync(string userName, string password)
        {
            return base.Channel.ObtenerDatosClienteAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.EmpresaNtLink[]> ObtenerEmpresasAsync(string userName, string password)
        {
            return base.Channel.ObtenerEmpresasAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TimbradoResponse> TimbraCfdiQrAsync(string userName, string password, string comprobante)
        {
            return base.Channel.TimbraCfdiQrAsync(userName, password, comprobante);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TimbradoResponse> TimbraCfdiQrSinSelloAsync(string userName, string password, string comprobante)
        {
            return base.Channel.TimbraCfdiQrSinSelloAsync(userName, password, comprobante);
        }
        
        public System.Threading.Tasks.Task<string> TimbraCfdiAsync(string userName, string password, string comprobante)
        {
            return base.Channel.TimbraCfdiAsync(userName, password, comprobante);
        }
        
        public System.Threading.Tasks.Task<string> TimbraCfdiSinSelloAsync(string userName, string password, string comprobante)
        {
            return base.Channel.TimbraCfdiSinSelloAsync(userName, password, comprobante);
        }
        
        public System.Threading.Tasks.Task<string> TimbraRetencionAsync(string userName, string password, string comprobante)
        {
            return base.Channel.TimbraRetencionAsync(userName, password, comprobante);
        }
        
        public System.Threading.Tasks.Task<string> TimbraRetencionSinSelloAsync(string userName, string password, string comprobante)
        {
            return base.Channel.TimbraRetencionSinSelloAsync(userName, password, comprobante);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TimbradoResponse> TimbraRetencionQrAsync(string userName, string password, string comprobante)
        {
            return base.Channel.TimbraRetencionQrAsync(userName, password, comprobante);
        }
        
        public System.Threading.Tasks.Task<string> CancelaRetencionAsync(string userName, string password, string uuid, string rfc, string motivo, string folioSustituto)
        {
            return base.Channel.CancelaRetencionAsync(userName, password, uuid, rfc, motivo, folioSustituto);
        }
        
        public System.Threading.Tasks.Task<string> CancelaCfdiAsync(string userName, string password, string uuid, string motivo, string folioSustituto, string rfc, string expresion, string rfcReceptor)
        {
            return base.Channel.CancelaCfdiAsync(userName, password, uuid, motivo, folioSustituto, rfc, expresion, rfcReceptor);
        }
        
        public System.Threading.Tasks.Task<string> CancelaCfdiOtrosPACsAsync(string uuid, string motivo, string folioSustituto, string rfcEmisor, string expresion, string rfcReceptor, string Base64Cer, string Base64Key, string PasswordKey)
        {
            return base.Channel.CancelaCfdiOtrosPACsAsync(uuid, motivo, folioSustituto, rfcEmisor, expresion, rfcReceptor, Base64Cer, Base64Key, PasswordKey);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.RespuestaCancelacion> CancelaCfdiRequestAsync(string userName, string password, string requestCancelacion, string expresion, string uuid, string rfcReceptor)
        {
            return base.Channel.CancelaCfdiRequestAsync(userName, password, requestCancelacion, expresion, uuid, rfcReceptor);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResultadoConsulta> ObtenerStatusUuidAsync(string userName, string password, string uuid)
        {
            return base.Channel.ObtenerStatusUuidAsync(userName, password, uuid);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResultadoConsulta> ObtenerStatusHashAsync(string userName, string password, string hash)
        {
            return base.Channel.ObtenerStatusHashAsync(userName, password, hash);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioTimbrado))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioTimbrado))
            {
                return new System.ServiceModel.EndpointAddress("http://pruebas.ntlink.com.mx:90/CertificadorWs40/ServicioTimbrado.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioTimbradoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioTimbrado);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioTimbradoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioTimbrado);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioTimbrado,
        }
    }
}
